<a href="https://colab.research.google.com/github/log-runner/comp0197-cw2/blob/main/preprocessing_1_dataloader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
from google.colab import drive
drive.mount('/content/drive/')
%cd /content/drive/MyDrive/UCL/Advanced Deep Learning/ADL_Group/

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
/content/drive/MyDrive/UCL/Advanced Deep Learning/ADL_Group


In [18]:
from preprocessing_1_dataloader import get_data
mixed_train_loader, val_loader, test_loader = get_data(0.2, 0.8, 0.2, 0.2)

all images are =  7393


In [19]:
# Unlabeled trained 
for i,data in enumerate(mixed_train_loader):
    inputs, labels = data
    print(i)
    print(inputs.shape)
    mask = torch.full((1, 1, 256, 256), -1)
    num_equal = torch.sum(labels == mask)
    print(num_equal/(256*256))
    print(labels[10]) # Check this and other indeces to find example of unlabelled and labelled example

0
torch.Size([100, 3, 256, 256])
tensor(84.)
tensor([[[-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         ...,
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.]]])
1
torch.Size([100, 3, 256, 256])
tensor(81.)
tensor([[[-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         ...,
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.]]])
2
torch.Size([100, 3, 256, 256])
tensor(78.)
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])
3
torch

KeyboardInterrupt: ignored

In [ ]:
# Labeled validation
for i,data in enumerate(val_loader):
    inputs, labels = data
    print(i)
    print(inputs.shape)

0
torch.Size([20, 3, 256, 256])
1
torch.Size([4, 3, 256, 256])


In [ ]:
# Labeled test
for i,data in enumerate(test_loader):
    inputs, labels = data
    print(i)
    print(inputs.shape)

0
torch.Size([20, 3, 256, 256])
1
torch.Size([5, 3, 256, 256])
